spring.application.name=payment-system

server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/mpesa_db?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# Flyway database migration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=false

# Hibernate now only validates schema (Flyway manages DDL)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

logging.level.com.mpesa=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=WARN

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=3600000